parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
#jacik env(DATABASE_URL): '///%kernel.project_dir%/var/database.db'

doctrine:
    dbal:
        #jacik driver: pdo_sqlite
        #jacik path: '%env(resolve:DATABASE_URL)%'
        #jacik server_version: '5.7'
        # configure these for your database server
        driver: pdo_mysql
        host: 127.0.0.1
        dbname: shop
        user: shop
        password: jacik

        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
