fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "jacik@toya.net.pl"
    sender_name: "Jacik"

  service:
    mailer: fos_user.mailer.twig_swift
  resetting:
    email:
      template:   email/password_resetting.email.twig
  registration:
    confirmation:
      template:   '@FOSUser/Registration/email.txt.twig'